version: '3'
services:
  db:
    image: postgres
    networks:
      - webnet
  web:
    image: localhost:5000/ist_web
    build: .
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.4"
          memory: 100M
      restart_policy:
        condition: on-failure
    expose:
      - "8000"
#    command: uwsgi --http :8000 --module MTproject.wsgi
    command: uwsgi --ini mysite_uwsgi.ini
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - webnet
#  visualizer:
#    image: dockersamples/visualizer:stable
#    ports:
#      - "8080:8080"
#    volumes:
#      - "/var/run/docker.sock:/var/run/docker.sock"
#    deploy:
#      placement:
#        constraints: [node.role == manager]
#    networks:
#      - webnet
  nginx:
    image: localhost:5000/ist_nginx
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - .:/app
    depends_on:
      - web
    links:
      - web:web
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  mongo:
    image: mongo
    volumes:
      - ./data/db:/data/db
    networks:
      - webnet
networks:
  webnet: